apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:  
        app: app1
    spec:
      volumes:
        - name: vol
      containers:
        - name: app1
          image: nginx-unprivileged:1.20.0-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: vol
              mountPath: /usr/share/nginx/html  # Fixed indentation
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
